version: 2

defaults: &defaults
  docker:
    - image: circleci/node:6.14-browsers

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: sudo npm install -g bower
      - run: sudo npm install -g gulp
      - run: bower install
      - run: gulp clean build
  publish_daily_build:
    <<: *defaults
    steps:
      - run: bash ./scripts/publish_dailybuild.sh

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - publish_daily_build:
          requires:
            - build
          filters:
            branches:
              only: master